"""Package settings."""
import logging


logger = logging.getLogger(__name__)

APP_NAME = "win-caffeine"

# GUI Settings
WINDOW_FIXED_WIDTH = 280
WINDOW_FIXED_HEIGHT = 280
WINDOW_POSITION = 200, 200
DEFAULT_APP_THEME = "light"


DEFAULT_STRATEGY_INDEX = 0
MULTITHREADING = True
START_IN_SUSPEND_MODE = False

STATUS_MESSAGE_DURATION_MSECONDS = 3000
HOUR = 60
MINUTE = 60
DEFAULT_DURATION_MINUTES = 2 * HOUR
DEFAULT_REFRESH_INTERVAL_SECONDS = 2 * MINUTE
MAX_INT = 2_147_483_647
MIN_INT = -MAX_INT - 1

